<?php

/**
 * This is the model base class for the table "tbl_quiz_answer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QuizAnswer".
 *
 * Columns in table "tbl_quiz_answer" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $quiz_id
 * @property string $correct_answer
 * @property string $answer_image
 *
 */
abstract class BaseQuizAnswer extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_quiz_answer';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QuizAnswer|QuizAnswers', $n);
	}

	public static function representingColumn() {
		return 'correct_answer';
	}

	public function rules() {
		return array(
			array('quiz_id', 'numerical', 'integerOnly'=>true),
			array('correct_answer, answer_image', 'safe'),
			array('quiz_id, correct_answer, answer_image', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, quiz_id, correct_answer, answer_image', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'quiz_id' => Yii::t('app', 'Quiz'),
			'correct_answer' => Yii::t('app', 'Correct Answer'),
			'answer_image' => Yii::t('app', 'Answer Image'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('quiz_id', $this->quiz_id);
		$criteria->compare('correct_answer', $this->correct_answer, true);
		$criteria->compare('answer_image', $this->answer_image, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}