<?php

/**
 * This is the model base class for the table "tbl_badge".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Badge".
 *
 * Columns in table "tbl_badge" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $image
 * @property string $criterium
 *
 */
abstract class BaseBadge extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_badge';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Badge|Badges', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, image, criterium', 'safe'),
			array('name, image, criterium', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, image, criterium', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'image' => Yii::t('app', 'Image'),
			'criterium' => Yii::t('app', 'Criterium'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('criterium', $this->criterium, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}