<?php

/**
 * This is the model base class for the table "tbl_quiz_answers_given".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QuizAnswersGiven".
 *
 * Columns in table "tbl_quiz_answers_given" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $game_id
 * @property integer $answer_id
 * @property integer $given_answer
 *
 */
abstract class BaseQuizAnswersGiven extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_quiz_answers_given';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QuizAnswersGiven|QuizAnswersGivens', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('game_id, answer_id, given_answer', 'numerical', 'integerOnly'=>true),
			array('game_id, answer_id, given_answer', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, game_id, answer_id, given_answer', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'game_id' => Yii::t('app', 'Game'),
			'answer_id' => Yii::t('app', 'Answer'),
			'given_answer' => Yii::t('app', 'Given Answer'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('game_id', $this->game_id);
		$criteria->compare('answer_id', $this->answer_id);
		$criteria->compare('given_answer', $this->given_answer);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}